apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://host.docker.internal:55929
    insecure-skip-tls-verify: true
  name: minikube
contexts:
- context:
    cluster: minikube
    user: gitlab-deployer
  name: minikube
current-context: minikube
users:
- name: gitlab-deployer
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpLVS1DeFc1Y0VGV01hVVQ2S3BHckR4ckdudzJ1cWdMdVZ1d1dqZDlyZ28ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoyMTAyMzI0MDgwLCJpYXQiOjE3ODY5NjQwODAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMGFhNjYyMGMtOWEzOC00NWJjLTg1MTItMDk1MTJiOTY1YjVkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJnaXRsYWItZGVwbG95ZXIiLCJ1aWQiOiI3NjU3OGNlNi1kMTFiLTQ5NWYtOTc5YS03NWQwNDM4YWMyMDMifX0sIm5iZiI6MTc4Njk2NDA4MCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmdpdGxhYi1kZXBsb3llciJ9.B6Zs849PW9V_RPWUMql72SEOg3iwfvazYitCcZNU3G-e69xxexJZLD50ToJk5ot9_nIdyEwireur3JBmP7ILGhoa5FQpvY9lVJcMeCKtaDH5mBdVRbrtgrGGafX-VIigqv11XtcPgV8dEMewoaw4KCZyBU_K1EYNG-Hn-aVNX7zmNm-YegeWArYurbFD6BlpKJSCR69E5MK-kebSAD0_2fEY0hOM_rXC3B9yu6PqtpLx2gpVZ3f6cIu5zXkEwjQeRJFbAXvbU27TTmkWDwVeNImyKVEGEZB3SetOicCr-HOO9OfsugiD7KYvhp5LagzEKRZUgMXGglNDyitan4oGBQ
