apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/sophie/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 12 Aug 2026 15:07:20 MSK
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://127.0.0.1:53058
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 12 Aug 2026 15:07:20 MSK
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
users:
- name: minikube
  user:
    client-certificate: /Users/sophie/.minikube/profiles/minikube/client.crt
    client-key: /Users/sophie/.minikube/profiles/minikube/client.key
