concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "ml-runner"
  url = "http://host.docker.internal:8088"
  id = 37
  token = "glrt-HXZyknEWCxWhKHoaPd72Wm86MQpwOjEKdDozCnU6MQ8.01.170ix8z21"
  token_obtained_at = 2026-08-12T14:13:06Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "python:3.9-slim"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["host.docker.internal:host-gateway"]
    shm_size = 0
    network_mtu = 0
